"""Visible on-image AI labels / watermarks via OCR."""

from __future__ import annotations

import re
from typing import Any

import cv2
import numpy as np
from PIL import Image

from ai_image_authenticator.application.analyzers.base import BaseAnalyzer
from ai_image_authenticator.domain.models import AnalyzerOutput
from ai_image_authenticator.domain.ports import OcrEngine

AI = r"a[il1!|]"  # OCR often reads the capital I in "AI" as l, 1 or |

# Disclosure phrasing counts wherever it appears in the OCR text.
# (pattern, display label, confidence weight 0-1)
DISCLOSURE_PATTERNS: list[tuple[str, str, float]] = [
    (rf"\bmade\s*with\s*{AI}\b", "Made with AI", 0.98),
    (rf"\bgenerated\s*(?:with|by)\s*{AI}\b", "Generated by AI", 0.96),
    (rf"\bcreated\s*(?:with|by)\s*{AI}\b", "Created with AI", 0.95),
    (rf"\b{AI}[\s\-]?generated\b", "AI-generated", 0.94),
    (rf"\b{AI}[\s\-]?modified\b", "AI-modified", 0.9),
    (rf"\b{AI}[\s\-]?assisted\b", "AI-assisted", 0.88),
    (rf"\bpartially\s*(?:generated|created)\s*(?:by|with)\s*{AI}\b", "Partially AI-generated", 0.9),
    (r"\bthis\s+image\s+was\s+generated\b", "This image was generated", 0.92),
]

# Generator names. Every name counts inside disclosure phrasing ("made with Midjourney",
# "Gemini-generated"). Distinctive names also count when OCR finds them in a badge region
# (corners, bottom strip). Ordinary words — runway, firefly, gemini, grok, imagen — never
# count on their own: "cleared to land on runway 27L" is not a disclosure.
# (pattern, display label, confidence weight, distinctive)
GENERATOR_NAMES: list[tuple[str, str, float, bool]] = [
    (r"midjourney", "Midjourney", 0.95, True),
    (r"dall[\s.\-·]?e(?:\s*[23])?", "DALL·E", 0.95, True),
    (r"stable\s*diffusion", "Stable Diffusion", 0.95, True),
    (r"adobe\s*firefly", "Adobe Firefly", 0.93, True),
    (r"leonardo\.?\s*ai", "Leonardo AI", 0.92, True),
    (r"ideogram", "Ideogram", 0.92, True),
    (r"flux\.?\s*1", "FLUX", 0.9, True),
    (r"nightcafe|novelai|seaart", "AI art platform", 0.85, True),
    (r"firefly", "Adobe Firefly", 0.93, False),
    (r"chatgpt|openai", "OpenAI / ChatGPT", 0.92, False),
    (r"imagen", "Imagen", 0.88, False),
    (r"grok", "Grok", 0.88, False),
    (r"gemini", "Gemini", 0.88, False),
    (r"runway(?:\s*(?:ml|gen[\s\-]?\d))?", "Runway", 0.88, False),
]
_DISCLOSURE_VERB = r"\b(?:made|generated|created|rendered)\s*(?:with|by|using)\s*"

# Content Credentials badges also appear on authentic camera captures (Leica, Pixel), so
# the text is reported as a provenance marker and never counted as an AI disclosure.
PROVENANCE_BADGE_PATTERNS: list[tuple[str, str]] = [
    (r"\bcontent\s*credentials\b", "Content Credentials"),
]


def _normalize_ocr_text(text: str) -> str:
    """Harden common OCR slips for AI tokens (Al / A1 / A| → ai)."""
    s = text.lower()
    s = re.sub(r"\ba[l1!|]\b", "ai", s)
    s = re.sub(r"made\s+with\s+a[l1!|]", "made with ai", s)
    s = re.sub(r"generated\s+(with|by)\s+a[l1!|]", r"generated \1 ai", s)
    s = re.sub(r"created\s+(with|by)\s+a[l1!|]", r"created \1 ai", s)
    s = re.sub(r"a[l1!|][\-\s]?generated", "ai-generated", s)
    s = re.sub(r"a[l1!|][\-\s]?assisted", "ai-assisted", s)
    s = re.sub(r"\s+", " ", s)
    return s


def _lines(chunks: list[str]) -> list[str]:
    return [_normalize_ocr_text(line) for chunk in chunks for line in chunk.split("\n") if line.strip()]


def match_disclosures(
    full_lines: list[str], badge_lines: list[str]
) -> tuple[dict[str, float], int, list[str]]:
    """Return (label -> confidence weight, matching line count, provenance badge labels).

    ``full_lines`` come from whole-frame OCR, ``badge_lines`` from corner/bottom-strip crops.
    """
    hits: dict[str, float] = {}
    votes = 0
    all_lines = full_lines + badge_lines

    def record(label: str, weight: float, count: int) -> None:
        nonlocal votes
        if count:
            hits[label] = max(hits.get(label, 0.0), weight)
            votes += count

    for pattern, label, weight in DISCLOSURE_PATTERNS:
        record(label, weight, sum(1 for line in all_lines if re.search(pattern, line)))
    for pattern, label, weight, distinctive in GENERATOR_NAMES:
        name = rf"\b(?:{pattern})\b"
        phrased = rf"{_DISCLOSURE_VERB}{name}|{name}[\s\-]*(?:generated|created)\b"
        count = sum(1 for line in all_lines if re.search(phrased, line))
        if distinctive:
            count += sum(1 for line in badge_lines if re.search(name, line))
        record(label, weight, count)
    provenance = [
        label
        for pattern, label in PROVENANCE_BADGE_PATTERNS
        if any(re.search(pattern, line) for line in all_lines)
    ]
    return hits, votes, provenance


def _badge_crops(gray: np.ndarray) -> list[np.ndarray]:
    """Crop common disclosure badge regions (corners + bottom strip)."""
    h, w = gray.shape
    crops: list[np.ndarray] = []
    y0 = int(h * 0.82)
    crops.append(gray[y0:, :])
    ch, cw = max(24, int(h * 0.22)), max(24, int(w * 0.35))
    crops.append(gray[:ch, :cw])
    crops.append(gray[:ch, w - cw :])
    crops.append(gray[h - ch :, :cw])
    crops.append(gray[h - ch :, w - cw :])
    return crops


class VisibleLabelOCR(BaseAnalyzer):
    id = "labels"
    name = "Visible AI Labels (OCR)"

    def __init__(self, ocr: OcrEngine | None = None) -> None:
        self._ocr = ocr

    def analyze(self, image: Image.Image, rgb: np.ndarray, raw_bytes: bytes, filename: str) -> AnalyzerOutput:
        findings: list[str] = []
        details: dict[str, Any] = {}
        ocr_text = ""
        available = False
        full_chunks: list[str] = []
        badge_chunks: list[str] = []

        ocr = self._ocr
        if ocr is None:
            from ai_image_authenticator.infrastructure.ocr import PytesseractOcrEngine

            ocr = PytesseractOcrEngine()

        try:
            if not ocr.is_available():
                raise RuntimeError("OCR engine unavailable")
            available = True
            gray = cv2.cvtColor(rgb, cv2.COLOR_RGB2GRAY)
            h, w = gray.shape
            max_side = 1600
            scale = min(1.0, max_side / max(h, w))
            if scale < 1.0:
                gray = cv2.resize(gray, (int(w * scale), int(h * scale)), interpolation=cv2.INTER_AREA)

            up = cv2.resize(gray, None, fx=1.5, fy=1.5, interpolation=cv2.INTER_CUBIC)
            thr = cv2.adaptiveThreshold(up, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, 31, 8)
            blur = cv2.GaussianBlur(up, (0, 0), 1.0)
            sharp = cv2.addWeighted(up, 1.6, blur, -0.6, 0)
            full_variants = [gray, up, thr, cv2.bitwise_not(thr), sharp]
            badge_variants = _badge_crops(up)

            configs = ("--psm 6", "--psm 11")
            for variants, sink in ((full_variants, full_chunks), (badge_variants, badge_chunks)):
                for arr in variants:
                    for cfg in configs:
                        try:
                            txt = ocr.image_to_string(arr, config=cfg)
                            if txt and txt.strip():
                                sink.append(txt)
                        except Exception:
                            continue
            ocr_text = "\n".join(full_chunks + badge_chunks)
            details["ocr_chars"] = len(ocr_text)
            details["ocr_preview"] = ocr_text[:800]
            details["ocr_variants"] = len(full_variants) + len(badge_variants)
        except Exception as e:
            details["ocr_error"] = str(e)
            findings.append(
                "OCR unavailable — install tesseract + pytesseract for on-image label detection"
            )
            return AnalyzerOutput(
                id=self.id,
                name=self.name,
                score=0.45,
                confidence=0.2,
                findings=findings,
                details=details,
            )

        hit_weights, votes, provenance_badges = match_disclosures(
            _lines(full_chunks), _lines(badge_chunks)
        )
        hits = list(hit_weights)

        details["ai_label_hits"] = hits
        details["hit_confidences"] = {k: round(v, 3) for k, v in hit_weights.items()}
        details["provenance_badge_hits"] = provenance_badges
        details["ocr_available"] = available
        # Lines re-read from the same pixels are not independent witnesses: reported, not scored
        details["ocr_agreement_votes"] = votes

        if hits:
            best = max(hit_weights.values())
            score = min(0.99, 0.86 + 0.025 * len(hits) + 0.05 * (best - 0.85))
            confidence = float(min(0.97, best))
            findings.append("Visible AI disclosure / generator text in pixels: " + ", ".join(hits))
            findings.append(
                f"OCR disclosure confidence≈{confidence:.0%} "
                f"(Al/A1-hardened; matched in {votes} OCR lines)"
            )
            findings.append("A visible disclosure in the raster is strong evidence of AI involvement")
        else:
            score = 0.42
            confidence = 0.45 if ocr_text.strip() else 0.3
            if ocr_text.strip():
                findings.append("OCR ran; no known AI disclosure phrases detected in visible text")
            else:
                findings.append("OCR returned little readable text")
        if provenance_badges:
            findings.append(
                "Content Credentials badge text visible — a provenance marker that also appears "
                "on authentic captures, not an AI disclosure"
            )

        return AnalyzerOutput(
            id=self.id,
            name=self.name,
            score=float(np.clip(score, 0, 1)),
            confidence=float(np.clip(confidence, 0, 1)),
            findings=findings,
            details=details,
        )
